import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import '@fontsource/tomorrow/100.css';
import '@fontsource/tomorrow/200.css';
import '@fontsource/tomorrow/300.css';
import '@fontsource/tomorrow/400.css';
import '@fontsource/tomorrow/500.css';
import '@fontsource/lato';

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Boslight",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} antialiased`}>{children}</body>
    </html>
  );
}
